# Generated by Django 3.2.15 on 2023-01-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custumer',
            name='tgl',
            field=models.CharField(max_length=50),
        ),
    ]
