# Generated by Django 3.2.15 on 2023-01-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0003_custumer_no_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custumer',
            name='keterangan',
            field=models.CharField(max_length=50),
        ),
    ]
